### PR TITLE
Update card.css

### PR DESCRIPTION
**Pull request by Dhananjay-12**
Removed line 38 as it was causing the cells to have gap.

### CODE REVIEW

**Comment by DreadKnight** [comment]
I've tested this and it still looks off like before, needs more work and testing. Also, in PR description you should usually mention the open issue that you're trying to fix, like #103 in this case. I can see what you've done in the "Files changed".

**Comment by Dhananjay-12** [comment]
Screenshot_20221126_112237

**Comment by Dhananjay-12** [comment]
How about this ?

**Comment by Dhananjay-12** [comment]
Well, I noticed now that those Icons have been position relative. But I guess using flexbox or grid might help. Can I try that?

**Comment by DreadKnight** [comment]
> Screenshot_20221126_112237

That's the idea, but make sure the red outline on the other card stays in place as well.
Also, modify css only to affect the contribution page, because the cards.css file is meant for this other page https://ancientbeast.com/documentation/?id=wars as it has some cards in it (having a different issue atm it seems).

**Pull request closed without merging**
