### PR TITLE
Gaps are removed.

### PR DESCRIPTION
**Pull request by VNxyz1**
remove gaps between items #103 

I updated "/units/cards.css" file. Now everything shouldwork.

In the previeous commit I eddited "/documentation/card.css".

### CODE REVIEW

**Comment by DreadKnight** [comment]
@VNxyz1 Editing that file will probably screw up the cards over here: https://ancientbeast.com/documentation/?id=units
The styling should probably be located around this area: https://github.com/FreezingMoon/AncientBeast-Website/blob/master/contribute/index.php#L26

**Comment by VNxyz1** [comment]
I added a new CSS Class, that only affects a specific area in this file: https://github.com/FreezingMoon/AncientBeast-Website/blob/master/contribute/index.php
It should not affect any other site. But I could probably do it with inline CSS if you want to ^^

**Comment by DreadKnight** [comment]
@VNxyz1 I'm aware, probably best to add it where I linked you to. It wasn't inline because of Google scoring stuff.

**Comment by VNxyz1** [comment]
It should work with my newest commit. Sorry for the misunderstanding :)

**Comment by DreadKnight** [comment]
@VNxyz1 No worries, looks good now 👍🏻

**Pull request merged**
