### PR TITLE
Another fixe for #33

### PR DESCRIPTION
**Pull request by ktiedt**
This includes an update to cards.php to make its view consistent with the JS view presented now.

Note: no easy way to test this locally, so please test before deploying :)

### CODE REVIEW

**Comment by DreadKnight** [comment]
At least it's no longer draconian. Ideally it should skip fields if undefined (like in case of upgrades etc).

**Comment by ktiedt** [comment]
The new patch essentially does, I believe

**Comment by DreadKnight** [comment]
When I tested it, it no longer broke, but it showed some upgrade lines as "undefined", should never have that word displayed on the cards :D

**Comment by ktiedt** [comment]
Ahh weird yeah it shouldn't have after my doc unlessmore then cost was
undefined

**Pull request merged**
