### PR TITLE
Update card.css

### PR DESCRIPTION
**Pull request by Dhananjay-12**
Removed line 38. As it was causing the cells to have gap in between

### CODE REVIEW

**Comment by DreadKnight** [comment]
You changed all the spacing, from 1 tab (4 spaces) to two spaces and made a mess. Please patch and tweak that stuff.

**Review by DreadKnight — CHANGES_REQUESTED** [review]
Please don't touch the spacing. All projects have a consistency set plus changes are not obvious anymore if you tweak all the lines in the file, so keep that in mind for any project.

**Comment by Dhananjay-12** [comment]
Hi , I'm sorry. My VS Code extension ha formatted the CSS file.

**Comment by Dhananjay-12** [comment]
I'll fix it.   T_T

**Pull request closed without merging**
