### PR TITLE
Fix link to contributing.md

### PR DESCRIPTION
**Pull request by Peritract**
The current link on the website is dead - it links to a heading that no longer exists.

I know this is a very minor PR, but if contributors are wanted, this will help funnel them in.

### CODE REVIEW

**Comment by DreadKnight** [comment]
@Peritract big thanks, thought anchor links can never break like this xD

**Comment by DreadKnight** [comment]
@Peritract Seems the anchor can never be the issue. That link it still broken, but I'll look into it asap.

**Comment by Peritract** [comment]
My bad; thanks for sorting it.

**Comment by DreadKnight** [comment]
@Peritract No worries, all good :)

**Pull request merged**
